UA-1378-TAQC/codeWars1378

src/main/java/org/academy/kata/implementation/HrushaNataliia/EightImpl.java
=> added implementation to Miles per gallon to kilometers per liter

src/main/java/org/academy/tasks/Task18.java, src/main/java/org/academy/tasks/Task9.java, src/main/java/org/academy/tasks/Task_5.java
=> 279 tasks correct way of printing array result 

src/main/java/org/academy/kata/implementation/viktoriiafylyk/FiveImpl.java
Perimeter of squares in a rectangle
=> Implementing perimeter method

src/main/java/org/academy/kata/implementation/roman50021/FiveImpl.java
=> Which x for that sum?

src/main/java/org/academy/kata/implementation/roman50021/FiveImpl.java
=> Find the smallest

src/main/java/org/academy/kata/implementation/Anat0li1/FiveImpl.java
=> Added zeros task

src/main/java/org/academy/kata/implementation/Anat0li1/FiveImpl.java
=> Added perimeter task

src/main/java/org/academy/kata/implementation/Anat0li1/FiveImpl.java
=> Added solve task

src/main/java/org/academy/kata/implementation/Anat0li1/SixImpl.java
=> Added ApproxFloat task

src/main/java/org/academy/kata/implementation/Anat0li1/SixImpl.java
=> Added Rainfall task

src/main/java/org/academy/kata/implementation/viktoriiafylyk/SixImpl.java
=> Implementing nbaСup method

src/main/java/org/academy/kata/implementation/Anat0li1/SixImpl.java
=> Added nbaCup task

src/main/java/org/academy/kata/implementation/Anat0li1/FiveImpl.java
=> Added GapInPrimes task

src/main/java/org/academy/kata/implementation/Anat0li1/FiveImpl.java
=> Added smallest task

src/main/java/org/academy/kata/implementation/roman50021/FiveImpl.java
=> Gap in Primes

src/main/java/org/academy/kata/implementation/roman50021/FiveImpl.java
Number of trailing zeros of N!
=> Number of trailing zeros of N!

src/main/java/org/academy/kata/implementation/roman50021/FiveImpl.java
Perimeter of squares in a rectangle
=> Perimeter of squares in a rectangle

src/main/java/org/academy/kata/implementation/keepCalmGirl/EightImpl.java
Given: height, width, and length of cuboid.
Return: cuboid volume.
=> Volume of cuboid task

src/main/java/org/academy/kata/implementation/MMykha/EightImpl.java
=> Implemented solution for Find numbers which are divisible by given number task

src/main/java/org/academy/kata/implementation/roman50021/EightImpl.java
=> Keep Hydrated!

src/main/java/org/academy/kata/implementation/roman50021/EightImpl.java
=> Volume of a Cuboid

src/main/java/org/academy/kata/implementation/keepCalmGirl/SixImpl.java
Given: town and strng data.
function: mean(town, strng) returns the average of rainfall for the city town and the strng data.
function: variance(town, strng) returns the rainfall variance for the city town and the strng data.
=> Rainfall task: calculate mean and variance for particular town.

src/main/java/org/academy/kata/implementation/roman50021/EightImpl.java
To square(root) or not to square(root)
=> To square(root) or not to square(root)

src/main/java/org/academy/kata/implementation/roman50021/EightImpl.java
Count of positives / sum of negatives
=> Count of positives / sum of negatives

src/main/java/org/academy/kata/implementation/roman50021/EightImpl.java
=> Convert a String to a Number!

src/main/java/org/academy/kata/implementation/roman50021/EightImpl.java
=> Formatting decimal places

src/main/java/org/academy/kata/implementation/roman50021/EightImpl.java
Find numbers which are divisible by given number
=> Find numbers which are divisible by given number

src/main/java/org/academy/kata/implementation/viktoriiafylyk/EightImpl.java
=> Implementing TwoDecimalPlaces  method (Formatting decimal places #0)

src/main/java/org/academy/kata/implementation/roman50021/SevenImpl.java
=> Looking for a benefactor

src/main/java/org/academy/kata/implementation/roman50021/SevenImpl.java
Sum of the first nth term of Series
=> Sum of the first nth term of Series

src/main/java/org/academy/kata/implementation/keepCalmGirl/SixImpl.java
Calculates results for a sequence of games for passed team.
The return format is:
"Team Name:W=nb of wins;D=nb of draws;L=nb of losses;Scored=nb;Conceded=nb;Points=nb"
=> Ranking NBA teams task. 

src/main/java/org/academy/kata/implementation/Anat0li1/EightImpl.java
=> Added KeepHydrated task

src/main/java/org/academy/kata/implementation/Anat0li1/EightImpl.java
=> Added getVolumeOfCuboid task

src/main/java/org/academy/kata/implementation/Anat0li1/EightImpl.java
squareOrSquareRoot is finished
=> Added squareOrSquareRoot task

src/main/java/org/academy/kata/implementation/Anat0li1/EightImpl.java
countPositivesSumNegatives is finished
=> Added countPositivesSumNegatives task

src/main/java/org/academy/kata/implementation/Anat0li1/EightImpl.java
=> Added stringToNumber task

src/main/java/org/academy/kata/implementation/Anat0li1/EightImpl.java
=> Added divisibleBy task

src/main/java/org/academy/kata/implementation/Anat0li1/SevenImpl.java
=> Added seriesSum task

src/main/java/org/academy/kata/implementation/Anat0li1/SixImpl.java
=> Added findNb task

src/main/java/org/academy/kata/implementation/viktoriiafylyk/SevenImpl.java
[Sum of the first nth term of Series]
=> Implementing seriesSum  method

src/main/java/org/academy/kata/implementation/Anat0li1/EightImpl.java
=> Added TwoDecimalPlaces task

src/test/java/org/academy/kata/SixTest.java, src/test/java/org/academy/kata/dataproviders/SixDataProvider.java
=> Added tests and data provider to findNb task

src/test/java/org/academy/kata/dataproviders/InputValidatorDataProvider.java, src/test/java/org/academy/util/data/InputValidatorTest.java
=>  Added tests to cover method, which validates double array correctness
